name: R

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        r-version: ['4.4.0']
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up R ${{ matrix.r-version }} on ${{ matrix.os }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}

      - name: Install libcurl-devel on Linux
        if: runner.os == 'Linux'
        run: sudo apt-get install -y libcurl4-openssl-dev
      
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
        
      - name: Install Pandoc
        run: Rscript -e 'install.packages("pandoc"); pandoc::pandoc_install()'
      
      - name: Check
        run: Rscript -e 'rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")'