name: R

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        r-version: ['4.4.0']
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up R ${{ matrix.r-version }} on ${{ matrix.os }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}

      - name: Install libcurl-devel on Linux
        if: runner.os == 'Linux'
        run: sudo apt-get install -y libcurl4-openssl-dev
      
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Install Pandoc on macOS
        if: runner.os == 'macOS'
        run: brew install pandoc
      
      - name: Install Pandoc on Linux
        if: runner.os == 'Linux'
        run: sudo apt-get install -y pandoc

      - name: Install Pandoc on Windows
        if: runner.os == 'Windows'
        run: |
          Invoke-WebRequest -Uri "https://github.com/jgm/pandoc/releases/download/3.3/pandoc-3.3-windows-x86_64.msi" -OutFile "pandoc-installer.msi"
          Start-Process msiexec.exe -ArgumentList '/i pandoc-installer.msi /quiet /norestart' -NoNewWindow -Wait
      
      - name: Check
        run: Rscript -e 'rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")'
